version: '3.7'

services:
  postgres:
    restart: on-failure
    image: postgres:10.6
    environment:
      # DATABASE_HOST: $DATABASE_HOST
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - 5432:5432
    container_name: fech_postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
  backend: &backend
    restart: always
    build: .
    image: fech/backend
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - nginx
    container_name: fech_backend
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=fech.settings.production
    entrypoint:
      - /django-entrypoint-prod.sh
  backend_dev:
    <<: *backend
    ports:
      - 8000:8000
    container_name: fech_backend_dev
    entrypoint:
      - /django-entrypoint-dev.sh
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=fech.settings.dev
  nginx:
    restart: on-failure
    build:
      context: .
      dockerfile: DockerfileNginx
    image: fech/backend-nginx
    container_name: fech_backend_nginx
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=admin@suplebest.cl
    network_mode: "host"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - .:/code

volumes:
  postgresdata: