# Generated by Django 2.2.5 on 2019-09-27 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20190927_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpageauthor',
            name='name',
        ),
        migrations.AddField(
            model_name='blogpageauthor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
