# Generated by Django 2.2.5 on 2019-10-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191001_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Content')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.content',),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de término'),
        ),
    ]
