# Generated by Django 2.2.5 on 2019-10-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191002_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='formatted_address',
        ),
    ]
