# Generated by Django 2.2.5 on 2019-10-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_event_formatted_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='latlng_address',
        ),
    ]
