# Generated by Django 2.2.6 on 2019-10-03 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0018_remove_event_latlng_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('notify_at', models.DateField(verbose_name='Fecha de notificación')),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='Objeto relacionado')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'blog'), ('model', 'event')), models.Q(('app_label', 'blog'), ('model', 'new')), models.Q(('app_label', 'blog'), ('model', 'benefit')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Contenido')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
