# Generated by Django 2.2.6 on 2019-10-03 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20191003_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 19, 40, 42, 134099, tzinfo=utc), verbose_name='Fecha de notificación'),
        ),
    ]
