# Generated by Django 2.2.6 on 2019-10-08 18:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20191003_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('notify_at', models.DateTimeField(default=datetime.datetime(2019, 10, 8, 18, 24, 50, 514671, tzinfo=utc), verbose_name='Fecha de notificación')),
                ('notified', models.BooleanField(default=False, verbose_name='Se ha notificado')),
                ('channel', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter')], default='FACEBOOK', max_length=32, verbose_name='Canal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='benefitnotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='eventnotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='newnotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 8, 18, 24, 50, 514077, tzinfo=utc), verbose_name='Fecha de notificación'),
        ),
        migrations.CreateModel(
            name='NewSharing',
            fields=[
                ('sharing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Sharing')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('new', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to='blog.New')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('blog.sharing', models.Model),
        ),
        migrations.CreateModel(
            name='EventSharing',
            fields=[
                ('sharing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Sharing')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to='blog.Event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('blog.sharing', models.Model),
        ),
        migrations.CreateModel(
            name='BenefitSharing',
            fields=[
                ('sharing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Sharing')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('benefit', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to='blog.Benefit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('blog.sharing', models.Model),
        ),
    ]
