# Generated by Django 2.2.6 on 2019-10-09 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20191008_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 19, 58, 45, 443147, tzinfo=utc), verbose_name='Fecha de notificación'),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='channel',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter')], default='FACEBOOK', max_length=32, verbose_name='Red social'),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='notify_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 19, 58, 45, 443631, tzinfo=utc), verbose_name='Fecha de notificación'),
        ),
    ]
