# Generated by Django 2.2.6 on 2019-10-10 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20191009_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='publish_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Publicar el'),
        ),
        migrations.AddField(
            model_name='content',
            name='unpublish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Despublicar el'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 17, 22, 21, 855895, tzinfo=utc), verbose_name='Fecha de notificación'),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='notify_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 17, 22, 21, 856379, tzinfo=utc), verbose_name='Fecha de notificación'),
        ),
    ]
