# Generated by Django 2.2.6 on 2019-10-10 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20191010_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publicar el'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 17, 24, 44, 501480, tzinfo=utc), verbose_name='Fecha de notificación'),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='notify_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 17, 24, 44, 501965, tzinfo=utc), verbose_name='Fecha de notificación'),
        ),
    ]
