# Generated by Django 2.2.6 on 2019-10-10 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20191010_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicar el'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de notificación'),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='notify_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de notificación'),
        ),
    ]
