# Generated by Django 2.2.6 on 2019-10-17 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20191010_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Beneficio', 'verbose_name_plural': 'Beneficios'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
        migrations.RemoveField(
            model_name='sharing',
            name='notified',
        ),
        migrations.RemoveField(
            model_name='sharing',
            name='notify_at',
        ),
        migrations.AddField(
            model_name='sharing',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
        migrations.AddField(
            model_name='sharing',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Se ha publicado'),
        ),
    ]
