# Generated by Django 2.2.9 on 2020-01-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20191107_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='description',
            field=models.TextField(help_text='Número máximo de carácteres depende de la red social utilizada.', max_length=1024, null=True, verbose_name='Descripción'),
        ),
    ]
