# Generated by Django 2.2.9 on 2020-01-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_sharing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='description',
            field=models.TextField(help_text='Número máximo de carácteres depende de la red social utilizada.', max_length=1024, verbose_name='Descripción'),
        ),
    ]
