# Generated by Django 2.2.9 on 2020-03-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_content_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ('-publish_at',), 'verbose_name': 'Beneficio', 'verbose_name_plural': 'Beneficios'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-publish_at',), 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('-publish_at',), 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterField(
            model_name='content',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Destacar el contenido para que aparezca al comienzo.', verbose_name='Destacar'),
        ),
    ]
