# Generated by Django 2.2.12 on 2020-04-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20200321_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='channel',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter')], default='INSTAGRAM', max_length=32, verbose_name='Red social'),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='description',
            field=models.TextField(help_text='Número máximo de carácteres depende de la red social utilizada (IG: 2200, Twitter: 280).', max_length=2048, null=True, verbose_name='Descripción'),
        ),
    ]
