# Generated by Django 2.2.12 on 2020-04-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_ccee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccee',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Fijado'),
        ),
    ]
