# Generated by Django 2.2.12 on 2020-04-21 03:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0039_auto_20200420_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccee',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Marca la casilla para fijar este contenido como importante.', verbose_name='Fijado'),
        ),
        migrations.AlterField(
            model_name='ccee',
            name='published',
            field=models.BooleanField(default=True, help_text='Marca la casilla para mostrar este contenido a los usuarios.', verbose_name='Publicado'),
        ),
        migrations.CreateModel(
            name='Transparency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('body', wagtail.core.fields.RichTextField(blank=True, verbose_name='Descripción')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='Dirección')),
                ('published', models.BooleanField(default=True, help_text='Marca la casilla para mostrar este contenido a los usuarios.', verbose_name='Publicado')),
                ('pinned', models.BooleanField(default=False, help_text='Marca la casilla para fijar este contenido como importante.', verbose_name='Fijado')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de publicación del documento.', verbose_name='Fecha de publicación')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wagtaildocs.Document', verbose_name='Documento')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wagtailimages.Image', verbose_name='Imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('body', wagtail.core.fields.RichTextField(blank=True, verbose_name='Descripción')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='Dirección')),
                ('published', models.BooleanField(default=True, help_text='Marca la casilla para mostrar este contenido a los usuarios.', verbose_name='Publicado')),
                ('pinned', models.BooleanField(default=False, help_text='Marca la casilla para fijar este contenido como importante.', verbose_name='Fijado')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wagtailimages.Image', verbose_name='Imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('body', wagtail.core.fields.RichTextField(blank=True, verbose_name='Descripción')),
                ('published', models.BooleanField(default=True, help_text='Marca la casilla para mostrar este contenido a los usuarios.', verbose_name='Publicado')),
                ('pinned', models.BooleanField(default=False, help_text='Marca la casilla para fijar este contenido como importante.', verbose_name='Fijado')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de publicación del documento.', verbose_name='Fecha de publicación')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='Dirección')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wagtaildocs.Document', verbose_name='Documento')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wagtailimages.Image', verbose_name='Imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
