# Generated by Django 2.2.12 on 2020-04-21 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20200421_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEFECHContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Content')),
            ],
            options={
                'verbose_name': 'CEFECH',
                'verbose_name_plural': 'CEFECH',
                'ordering': ('-publish_at',),
            },
            bases=('blog.content',),
        ),
        migrations.AlterModelOptions(
            name='archive',
            options={'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.AlterModelOptions(
            name='ccee',
            options={'verbose_name': 'CCEE', 'verbose_name_plural': 'CCEEs'},
        ),
        migrations.AlterModelOptions(
            name='ong',
            options={'verbose_name': 'ONG', 'verbose_name_plural': 'ONGs'},
        ),
        migrations.AlterModelOptions(
            name='transparency',
            options={'verbose_name': 'Transparencia', 'verbose_name_plural': 'Transparencias'},
        ),
    ]
